version: "2"
services:
    database:
        image: postgres:9.6.3
        container_name: school-database
        restart: unless-stopped
        environment:
            - POSTGRES_DB=school
            - POSTGRES_USER=school
            - POSTGRES_PASSWORD=school
        expose:
            - "5432"
        volumes:
            - "school_db_data:/var/lib/postgresql/data"
    django:
        build:
            context: .
            dockerfile: ./compose/django/Dockerfile
        command: bash -c "/app/start-django-dev.sh"
        container_name: school-django
        restart: unless-stopped
        volumes:
            - "./src:/app/src"
        links:
            - database
        depends_on:
            - database
        environment:
            - DEBUG

volumes:
  school_db_data:
